### ISSUE TITLE
Error in exporting keras model

### ISSUE THREAD

**Issue by thirubeyond** [triton-inference-server/model_navigator#12]
Hi,

I have a keras model which I loaded and export to nav. I get error while exporting as below. any tips of finding out what could be wrong.

`
validation data loaded
shape is: (1, 100, 128, 128, 2)
model loaded
2022-06-21 04:59:56 INFO     Navigator API: ============================== Config parameters ===================================================
2022-06-21 04:59:56 INFO     Navigator API: {'framework': 'tensorflow2', 'model_name': 'brain_tumor_tf2_model', 'workdir': '/opt/model-navigator/navigator_workdir', 'override_workdir': True, 'target_formats': ['onnx'], 'sample_count': 100, 'disable_git_info': False, 'batch_dim': 0, 'seed': 0, 'timestamp': '2022-06-21T03:59:56.321501', '_input_names': ['input_1'], '_output_names': ['conv2d_22'], 'from_source': True, 'max_workspace_size': 8589934592, 'target_precisions': ['fp32', 'fp16'], 'minimum_segment_size': 3, 'target_device': 'cpu', 'opset': 14, 'onnx_runtimes': ['CPUExecutionProvider']}
2022-06-21 04:59:56 INFO     Navigator API: ============================== Pipeline TensorFlow 2 pipeline started ==============================
2022-06-21 04:59:56 INFO     Navigator API: ============================== Infer input metadata. ===============================================
2022-06-21 04:59:56 INFO     Navigator API: ============================== Fetch input model data ==============================================
2022-06-21 04:59:56 WARNING  Navigator API: No TRT (min, opt, max) values for axes provided. Using values derived from the dataloader: {'input_1': {0: (1, 1, 1), 1: (100, 100, 100), 2: (128, 128, 128), 3: (128, 128, 128), 4: (2, 2, 2)}}.
2022-06-21 04:59:56 WARNING  Navigator API: No dynamic axes provided. Using values derived from the dataloader: defaultdict(<class 'list'>, {})
2022-06-21 04:59:56 INFO     Navigator API: ============================== Infer output metadata. ==============================================
2022-06-21 04:59:56 ERROR    Navigator API: UserError raised.
2022-06-21 04:59:56 WARNING  Navigator API: External errors are usually caused by incompatibilites between the model and the target formats and/or runtimes.
2022-06-21 04:59:56 ERROR    Navigator API: Traceback (most recent call last):
  File "/opt/model-navigator/model_navigator/framework_api/commands/infer_metadata.py", line 127, in __call__
    output = runner.infer(profiling_sample)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/runner.py", line 170, in infer
    return self.infer_impl(feed_dict, *args, **kwargs)
  File "/opt/model-navigator/model_navigator/framework_api/runners/tf.py", line 59, in infer_impl
    if isinstance(self.model._saved_model_inputs_spec, Mapping):
AttributeError: 'str' object has no attribute '_saved_model_inputs_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/model-navigator/model_navigator/framework_api/commands/core.py", line 81, in transform
    self.output = self.__call__(**kwargs)
  File "/opt/model-navigator/model_navigator/framework_api/commands/infer_metadata.py", line 127, in __call__
    output = runner.infer(profiling_sample)
  File "/opt/model-navigator/model_navigator/framework_api/exceptions.py", line 27, in __exit__
    raise UserError(exc_value)
model_navigator.framework_api.exceptions.UserError: 'str' object has no attribute '_saved_model_inputs_spec'
`

**Comment by thirubeyond** [comment]
found the issue in user code and resolved
