### ISSUE TITLE
appropriate polygraphy and tensorRT version for main branch

### ISSUE THREAD

**Issue by Learndeligent** [triton-inference-server/model_navigator#20]
Hi Trtion Team:

when I ran examples/torch/linear/optimize.py, I encournted the err as:

```bash
2023-05-10 17:44:17,576 INFO     Navigator:     [W] Unable to determine GPU memory usage
    [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
    Traceback (most recent call last):
      File "/opt/conda/envs/py38/bin/polygraphy", line 8, in <module>
        sys.exit(main())
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/tools/_main.py", line 70, in main
        status = selected_tool.run(args)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/tools/base/tool.py", line 171, in run
        status = self.run_impl(args)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/tools/convert/convert.py", line 98, in run_impl
        with self.arg_groups[TrtLoadEngineBytesArgs].load_engine_bytes() as serialized_engine:
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/tools/args/backend/trt/loader.py", line 575, in load_engine_bytes
        return loader()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
        return self.call_impl(*args, **kwargs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/util/util.py", line 694, in wrapped
        return func(*args, **kwargs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/backend/trt/loader.py", line 492, in call_impl
        ret, owns_network = util.invoke_if_callable(self._network)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/util/util.py", line 663, in invoke_if_callable
        ret = func(*args, **kwargs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
        return self.call_impl(*args, **kwargs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/util/util.py", line 694, in wrapped
        return func(*args, **kwargs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/backend/trt/loader.py", line 207, in call_impl
        with util.FreeOnException(super().call_impl()) as (builder, network, parser):
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/util/util.py", line 694, in wrapped
        return func(*args, **kwargs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/backend/trt/loader.py", line 127, in call_impl
        with util.FreeOnException(create_network(explicit_batch=self.explicit_batch)) as (builder, network):
      File "<string>", line 3, in create_network
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
        return self.call_impl(*args, **kwargs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/util/util.py", line 694, in wrapped
        return func(*args, **kwargs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/polygraphy/backend/trt/loader.py", line 100, in call_impl
        with util.FreeOnException([trt.Builder(trt_util.get_trt_logger())]) as (builder,):
    TypeError: pybind11::init(): factory function returned nullptr
```

Here is my pip pkg version:
```bash
polygraphy: 0.47.1
tensorrt: 8.6.1
torch: 2.0.1
```

commands to reproduce(refer to model_navigator/examples/torch/linear/README.md):
```bash
./optimize.py --output-path linear.nav
```

**Comment by jkosek** [comment]
Hi @Learndeligent,

Could you provide following information:
1. What is the CUDA version you are using? 
2. Is the script executed in OS or Docker container? Could you provide details of execution environment?

Thanks!
