### ISSUE TITLE
There is an error using `nav.triton.model_repository.add_model_from_package`

### ISSUE THREAD

**Issue by msclock** [triton-inference-server/model_navigator#24]
Thanks for your hard working on this remarkable tool. And I encountered an error when I execute the command `./optimize.py  --model-name classification --max-sequence-length=10`.
```python
#!/usr/bin/env python3

import math
import os

# https://stackoverflow.com/questions/62691279/how-to-disable-tokenizers-parallelism-true-false-warning
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import argparse
import itertools
import pathlib

import numpy as np
from datasets import load_dataset
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, DataCollatorWithPadding, TensorType
from transformers import AutoModelForSequenceClassification
from transformers.onnx.features import FeaturesManager
import model_navigator as nav


def get_model(model_name: str):
    model = AutoModelForSequenceClassification.from_pretrained(model_name)
    model.config.return_dict = True
    return model


def get_dataloader(
    model_name: str,
    dataset_name: str,
    max_batch_size: int,
    num_samples: int,
    max_sequence_length: int,
):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    if max_sequence_length == -1:
        max_sequence_length = getattr(tokenizer, "model_max_length", 512)

        if max_sequence_length > 512:
            max_sequence_length = 512

    model = FeaturesManager.get_model_from_feature(
        feature="sequence-classification", model=model_name
    )
    _, model_onnx_config = FeaturesManager.check_supported_model_or_raise(
        model=model, feature="sequence-classification"
    )
    onnx_config = model_onnx_config(model.config)
    input_names = tuple(onnx_config.inputs.keys())
    dataset = load_dataset(dataset_name)["train"]

    def preprocess_function(examples):
        return tokenizer(
            examples["content"], truncation=True, max_length=max_sequence_length
        )

    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    tokenized_dataset = tokenized_dataset.remove_columns(
        [c for c in tokenized_dataset.column_names if c not in input_names]
    )
    dataloader = DataLoader(
        tokenized_dataset,
        batch_size=max_batch_size,
        collate_fn=DataCollatorWithPadding(
            tokenizer=tokenizer,
            padding=True,
            max_length=max_sequence_length,
            return_tensors=TensorType.PYTORCH,
        ),
    )

    return [sample for sample, _ in zip(dataloader, range(num_samples))]


def get_verify_function():
    def verify_func(ys_runner, ys_expected):
        """Verify that at least 99% max probability tokens match on any given batch."""
        for y_runner, y_expected in zip(ys_runner, ys_expected):
            if not all(
                np.mean(a.argmax(axis=2) == b.argmax(axis=2)) > 0.99
                for a, b in zip(y_runner.values(), y_expected.values())
            ):
                return False
        return True

    return verify_func


def get_configuration(
    model_name: str,
    batch_size: int,
    max_sequence_length: int,
):
    model = FeaturesManager.get_model_from_feature(
        model=model_name,
        feature="sequence-classification",
    )
    _, model_onnx_config = FeaturesManager.check_supported_model_or_raise(
        model=model,
        feature="sequence-classification",
    )
    onnx_config = model_onnx_config(model.config)
    input_names = tuple(onnx_config.inputs.keys())
    output_names = tuple(onnx_config.outputs.keys())
    dynamic_axes = {
        name: axes
        for name, axes in itertools.chain(
            onnx_config.inputs.items(),
            onnx_config.outputs.items(),
        )
    }
    opset = onnx_config.default_onnx_opset

    tensorrt_profile = nav.TensorRTProfile()
    for k in input_names:
        tensorrt_profile.add(
            k,
            (1, max_sequence_length),
            (math.ceil(batch_size / 2), max_sequence_length),
            (batch_size, max_sequence_length),
        )

    optimization_profile = nav.OptimizationProfile(
        max_batch_size=batch_size,
        batch_sizes=[
            1,
            math.ceil(batch_size / 2),
            batch_size,
        ],
        stability_percentage=15,
        max_trials=5,
        throughput_cutoff_threshold=0.1,
    )

    configuration = {
        "input_names": input_names,
        "output_names": output_names,
        "sample_count": 10,
        "optimization_profile": optimization_profile,
        "custom_configs": [
            nav.TorchConfig(
                jit_type=nav.JitType.TRACE,
                strict=False,
            ),
            nav.OnnxConfig(
                opset=opset,
                dynamic_axes=dynamic_axes,
            ),
            nav.TensorRTConfig(
                precision=(nav.TensorRTPrecision.FP32),
                max_workspace_size=2 * 1024 * 1024 * 1024,
                trt_profile=tensorrt_profile,
            ),
        ],
    }
    return configuration


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--workspace",
        type=str,
        default=".navigator_workspace",
        help="navigator cache workspace",
    )
    parser.add_argument(
        "--input-model",
        type=str,
        default="uer/albert-base-chinese-cluecorpussmall",
        help="input model",
    )
    parser.add_argument(
        "--model-name",
        type=str,
        required=True,
        help="sub dir model name in model store model_repository folder",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=4,
        help="batch size on model",
    )
    parser.add_argument(
        "--max-sequence-length",
        type=int,
        default=-1,
        help="max input text sequence length on model",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        help="device = None or 'cpu' or 0 or '0' or '0,1,2,3'",
    )
    parser.add_argument(
        "--min-top1-accuracy",
        type=float,
        default=0.9,
    )
    parser.add_argument(
        "--model-repository",
        type=str,
        default=f".model_repository",
        help="model repository folder serving on tirton",
    )
    return parser.parse_args()


def main(FLAGS):
    dataset_name = "madao33/new-title-chinese"
    num_samples = 10

    model = get_model(FLAGS.input_model)
    dataloader = get_dataloader(
        model_name=FLAGS.input_model,
        dataset_name=dataset_name,
        max_batch_size=FLAGS.batch_size,
        num_samples=num_samples,
        max_sequence_length=FLAGS.max_sequence_length,
    )
    verify_func = get_verify_function()
    configuration = get_configuration(
        model_name=FLAGS.input_model,
        batch_size=FLAGS.batch_size,
        max_sequence_length=FLAGS.max_sequence_length,
    )

    package = nav.torch.optimize(
        model=model,
        dataloader=dataloader,
        # verify_func=verify_func,
        target_device=nav.DeviceKind.CPU
        if str(FLAGS.device) == "cpu"
        else nav.DeviceKind.CUDA,
        debug=True,
        verbose=True,
        workspace=pathlib.Path(FLAGS.workspace) / FLAGS.model_name,
        **configuration,
    )

    import shutil

    shutil.rmtree(
        pathlib.Path(FLAGS.model_repository) / FLAGS.model_name,
        ignore_errors=True,
    )

    nav.triton.model_repository.add_model_from_package(
        model_repository_path=pathlib.Path(FLAGS.model_repository),
        model_name=FLAGS.model_name,
        package=package,
    )


if __name__ == "__main__":
    main(parse_args())

```
Here is my error stack, and it reports the failure of conversion from TorchConfig to a dict with the syntax `**`.
```bash
Traceback (most recent call last):
  File "./optimize.py", line 258, in <module>
  File "./optimize.py", line 250, in main
    model_repository_path=pathlib.Path(FLAGS.model_repository),
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/triton/model_repository.py", line 202, in add_model_from_package
    if package.config.batch_dim not in [0, None]:
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/package/package.py", line 103, in config
    config_dict["custom_configs"] = self._get_custom_configs(self.status.config["custom_configs"])
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/package/package.py", line 315, in _get_custom_configs
    obj = custom_config_class.from_dict(fields)  # pytype: disable=not-instantiable
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/api/config.py", line 452, in from_dict
    return cls(**config_dict)
TypeError: ABCMeta object argument after ** must be a mapping, not TorchConfig
```

So I have to add the patching codes to the logic by the following codes: 
```python
#..... Same as the above

    import shutil

    shutil.rmtree(
        pathlib.Path(FLAGS.model_repository) / FLAGS.model_name,
        ignore_errors=True,
    )
    # Here are the patching codes
    package.status.config["custom_configs"] = {
        k: conf.to_dict() for k, conf in package.status.config["custom_configs"].items()
    }
    nav.triton.model_repository.add_model_from_package(
        model_repository_path=pathlib.Path(FLAGS.model_repository),
        model_name=FLAGS.model_name,
        package=package,
    )


if __name__ == "__main__":
    main(parse_args())
```

**Comment by jkosek** [comment]
Thanks @msclock. We are going to prepare the fix.

**Comment by msclock** [comment]
Waiting for the fix in the next release.😃

**Comment by jkosek** [comment]
The new version with fix has been released.

**Comment by msclock** [comment]
@jkosek Thank you for the rapid fix and I've used the latest version of the 73B0F3DFC. The logic is very clean now.

I will continue to follow up on the issue of feedback, once again very grateful for the quick feedback.
