### ISSUE TITLE
TypeError: pybind11::init(): factory function returned nullptr

### ISSUE THREAD

**Issue by wanglong001** [triton-inference-server/model_navigator#34]
I want to use this repo in docker(**_nvcr.io/nvidia/tritonserver:22.12-py3_**)
# steps
```
python3 -m pip install triton-model-navigator
```
_**Successfully installed aiohttp-3.9.0 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 brotli-1.1.0 coloredlogs-15.0.1 cuda-python-12.3.0 dacite-1.8.1 fire-0.5.0 flatbuffers-23.5.26 frozenlist-1.4.0 gevent-23.9.1 geventhttpclient-2.0.2 greenlet-3.0.1 grpcio-1.59.3 humanfriendly-10.0 jsonlines-4.0.0 mpmath-0.19 multidict-6.0.4 onnx-1.14.1 onnx-graphsurgeon-0.3.27 onnxruntime-gpu-1.16.3 onnxscript-0.1.0.dev20231121 packaging-23.2 polygraphy-0.49.0 protobuf-3.20.3 psutil-5.9.6 py-cpuinfo-9.0.0 pynvml-11.5.0 python-rapidjson-1.13 python-slugify-8.0.1 pyyaml-6.0.1 sympy-1.12 tabulate-0.9.0 tensorrt-8.6.1.post1 termcolor-2.3.0 text-unidecode-1.3 triton-model-navigator-0.7.4 tritonclient-2.39.0 typing-extensions-4.8.0 wrapt-1.14.1 yarl-1.9.3 zope.event-5.0 zope.interface-6.1**_

```
python3 test.py
```

## test.py
```
import pathlib

import model_navigator as nav
import numpy as np


def dataloader():
    return [np.random.rand(1, 3, 224, 224).astype("float32")]


onnx_model = r"model.onnx"
onnx_package = nav.onnx.optimize(
    model=onnx_model,
    dataloader=dataloader(),
    target_formats=(nav.Format.TENSORRT,),
    workspace=pathlib.Path("onnx_workspace"),
    custom_configs=[nav.TensorRTConfig(precision=(nav.TensorRTPrecision.FP32,))],
)
nav.package.save(onnx_package, "onnx_linear.plan", override=True)
```

**2023-11-21 09:18:02 WARNING  Navigator: Command finished with ModelNavigatorUserInputError. The error is considered as external error. Usually caused by incompatibilities between the model and the target formats and/or runtimes. Please review the command output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/model_navigator/pipelines/pipeline.py", line 108, in _execute_unit
    command_output = execution_unit.command().run(\*\*input_parameters)  # pytype: disable=not-instantiable
  File "/usr/local/lib/python3.8/dist-packages/model_navigator/commands/base.py", line 116, in run
    output = self._run(\*args,  \*\*_filter_dict_for_func(kwargs, self._run))
  File "/usr/local/lib/python3.8/dist-packages/model_navigator/commands/convert/onnx/onnx2trt.py", line 149, in _run
    conversion_max_batch_size = self._execute_conversion(
  File "/usr/local/lib/python3.8/dist-packages/model_navigator/commands/convert/base.py", line 75, in _execute_conversion
    conversion_max_batch_size = cls._execute_single_conversion(
  File "/usr/local/lib/python3.8/dist-packages/model_navigator/commands/convert/base.py", line 90, in _execute_single_conversion
    convert_func(get_args())
  File "/usr/local/lib/python3.8/dist-packages/model_navigator/commands/convert/onnx/onnx2trt.py", line 150, in <lambda>
    convert_func=lambda args: context.execute_external_runtime_script(onnx2trt.__file__, args),
  File "/usr/local/lib/python3.8/dist-packages/model_navigator/commands/execution_context.py", line 188, in execute_external_runtime_script
    self.execute_cmd(cmd, allow_failure=allow_failure)
  File "/usr/local/lib/python3.8/dist-packages/model_navigator/commands/execution_context.py", line 231, in execute_cmd
    raise ModelNavigatorUserInputError(
model_navigator.exceptions.ModelNavigatorUserInputError: Processes exited with error code: 1. Command to reproduce error: /bin/bash trt-fp32/reproduce_conversion.sh**

```
/bin/bash trt-fp32/reproduce_conversion.sh
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[W] Unable to determine GPU memory usage
[W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
  File "trt-fp32/reproduce_conversion.py", line 127, in <module>
    fire.Fire(convert)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "trt-fp32/reproduce_conversion.py", line 105, in convert
    network = network_from_onnx_path(exported_model_path.as_posix(), flags=onnx_parser_flags)
  File "<string>", line 3, in network_from_onnx_path
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 223, in call_impl
    builder, network, parser = super().call_impl()
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 138, in call_impl
    builder, network = create_network(strongly_typed=self.strongly_typed)
  File "<string>", line 3, in create_network
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 103, in call_impl
    builder = trt.Builder(trt_util.get_trt_logger())
TypeError: pybind11::init(): factory function returned nullptr
```

**Comment by jkosek** [comment]
Hi @wanglong001. 

Could you provide additional information:
- How do you run the Docker container?
- Is NVIDIA GPU visible inside the container?
- What is CUDA and driver version you are using?

We have ran some test inside mentioned container running simple ONNX model that we are using for tests. There was no issue. Here is the code:
```
import pathlib

import model_navigator as nav
import numpy as np

dataloader = [
        {
            "X": np.random.rand(3, 3, 8, 8).astype(np.dtype("float32")),
        }
        for _ in range(2)
    ]

onnx_model = pathlib.Path().cwd() / "tests" / "assets" / "models" / "identity.onnx"

onnx_package = nav.onnx.optimize(
    model=onnx_model,
    dataloader=dataloader,
    target_formats=(nav.Format.TENSORRT,),
    custom_configs=(nav.OnnxConfig(opset=13), nav.TensorRTConfig(precision=(nav.TensorRTPrecision.FP32,))),
    verbose=True
)
nav.package.save(onnx_package, "onnx_linear.nav", override=True)
```
The steps required for execution:

1. Run Docker container:
```
docker run -it --gpus 1 nvcr.io/nvidia/tritonserver:22.12-py3 bash
```
2. Install Model Navigator:
```
pip install -U --extra-index-url https://pypi.ngc.nvidia.com triton-model-navigator
```
3. Clone Model Navigator repository (required to get the ONNX model used in test):
```
git clone https://github.com/triton-inference-server/model_navigator.git
```
4. Switch directory to cloned repository:
```
cd model_navigator
```
5. Place the code in `test.py` file
6. Execute the script:
```
python3 test.py
```
Please, let us know the result of the execution. Thanks!

**Comment by wanglong001** [comment]
@jkosek Thanks, according to your demo can run normally, 
and I want to run on wsl2, in this environment,
![image](https://github.com/triton-inference-server/model_navigator/assets/14817376/3e34eb2e-f162-4cdb-8a13-3ceaddbbd60f)

your demo also reports this error, is there any solution

```
python test.py
2023-11-23 10:38:47 INFO     Navigator: Creating workspace at /home/wzl/github/model_navigator/navigator_workspace
2023-11-23 10:38:47 INFO     Navigator: Initializing log file.
2023-11-23 10:38:47 INFO     Navigator: ============================================== Common config parameters ==============================================
2023-11-23 10:38:47 INFO     Navigator: {
    "framework": "onnx",
    "target_formats": [
        "onnx",
        "trt"
    ],
    "target_device": "cuda",
    "sample_count": 100,
    "optimization_profile": {
        "max_batch_size": null,
        "batch_sizes": null,
        "window_size": 50,
        "stability_percentage": 10.0,
        "stabilization_windows": 3,
        "min_trials": 3,
        "max_trials": 10,
        "throughput_cutoff_threshold": 0.05
    },
    "runner_names": [
        "TensorRTCUDAGraph",
        "TensorRT",
        "OnnxCUDA",
        "OnnxTensorRT",
        "PythonRunner"
    ],
    "batch_dim": 0,
    "seed": 0,
    "_input_names": null,
    "_output_names": null,
    "from_source": true,
    "custom_configs": {
        "Onnx": {
            "custom_args": {},
            "opset": 13,
            "dynamo_export": false,
            "dynamic_axes": null,
            "onnx_extended_conversion": false,
            "graph_surgeon_optimization": true
        },
        "TensorRT": {
            "custom_args": {},
            "trt_profiles": null,
            "trt_profile": null,
            "precision": [
                "fp32"
            ],
            "precision_mode": "hierarchy",
            "max_workspace_size": 8589934592,
            "run_max_batch_size_search": null,
            "optimization_level": null,
            "compatibility_level": null,
            "onnx_parser_flags": null
        }
    },
    "verbose": true,
    "debug": false
}
DEPRECATION: Loading egg at /home/wzl/miniconda3/lib/python3.11/site-packages/onnx_tensorrt-8.6.1-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
2023-11-23 10:38:49 INFO     Navigator: ========================================== Pipeline 'Preprocessing' started ==========================================
2023-11-23 10:38:49 INFO     Navigator: ======================================== Command 'InferInputMetadata' started ========================================
2023-11-23 10:38:49 INFO     Navigator: ======================================= Command 'FetchInputModelData' started ========================================
2023-11-23 10:38:49 WARNING  Navigator: Requested sample_count (100) is larger than the number of available samples (2). Using 2 samples.
2023-11-23 10:38:49 INFO     Navigator: Collecting input samples for model.
2023-11-23 10:38:49 INFO     Navigator: Saving samples into the workspace.
2023-11-23 10:38:49 INFO     Navigator: ======================================= Command 'InferOutputMetadata' started ========================================
2023-11-23 10:38:49 INFO     Navigator: Using default runners: `['OnnxCPU', 'OnnxCUDA', 'OnnxTensorRT']` for format `onnx`.
2023-11-23 10:38:49 INFO     Navigator: Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
2023-11-23 10:38:49 INFO     Navigator: ======================================= Command 'FetchOutputModelData' started =======================================
2023-11-23 10:38:49 INFO     Navigator: Using default runners: `['OnnxCPU', 'OnnxCUDA', 'OnnxTensorRT']` for format `onnx`.
2023-11-23 10:38:49 INFO     Navigator: Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
2023-11-23 10:38:49 INFO     Navigator: Disable fallback for ONNX execution provider.
2023-11-23 10:38:49 INFO     Navigator: Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
2023-11-23 10:38:49 INFO     Navigator: Disable fallback for ONNX execution provider.
2023-11-23 10:38:49 INFO     Navigator: Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
2023-11-23 10:38:49 INFO     Navigator: Disable fallback for ONNX execution provider.
2023-11-23 10:38:49 INFO     Navigator: ============================================ Command 'CopyModel' started =============================================
2023-11-23 10:38:49 INFO     Navigator: =================================== Pipeline 'Find Device Max Batch Size' started ====================================
2023-11-23 10:38:49 INFO     Navigator: ========================================= Command 'FindMaxBatchSize' started =========================================
2023-11-23 10:38:49 INFO     Navigator: Command: /home/wzl/miniconda3/bin/python onnx/reproduce_max_batch_size-onnxrtcudarunner.py --batch_dim '0' --results_path '/tmp/tmpsl1axgai' --optimization_profile '{"max_batch_size": None, "batch_sizes": None, "window_size": 1, "stability_percentage": 10.0, "stabilization_windows": 1, "min_trials": 1, "max_trials": 1, "throughput_cutoff_threshold": -2}' --model_path 'onnx/model.onnx' --runner_name 'OnnxCUDA' --input_metadata '{"metadata": [{"name": "X", "shape": (-1, 3, 8, 8), "dtype": "float32"}], "pytree_metadata": {"metadata": {"X": "X"}, "tensor_type": "numpy"}, "is_legacy": False}' --output_metadata '{"metadata": [{"name": "Y", "shape": (-1, 3, 8, 8), "dtype": "float32"}], "pytree_metadata": {"metadata": {"Y": "Y"}, "tensor_type": "numpy"}, "is_legacy": False}'
2023-11-23 10:38:49 INFO     Navigator: Command output:
    2023-11-23 10:38:49 INFO     Navigator: Creating ONNX-Runtime Inference Session with providers: ['CUDAExecutionProvider']
    2023-11-23 10:38:50.990992576 [E:onnxruntime:, inference_session.cc:1798 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudnnStatus_t; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED ; GPU=0 ; hostname=wzl ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=172 ; expr=cudnnCreate(&cudnn_handle_);


    2023-11-23 10:38:50 INFO     Navigator: Max batch size search finished with success.
2023-11-23 10:38:51 INFO     Navigator: Max batch size not found. Please review the log.
2023-11-23 10:38:51 INFO     Navigator: ======================================= Pipeline 'TensorRT Conversion' started =======================================
2023-11-23 10:38:51 INFO     Navigator: ========================================= Command 'ConvertONNX2TRT' started ==========================================
2023-11-23 10:38:51 INFO     Navigator: ONNX to TRT conversion started
2023-11-23 10:38:51 INFO     Navigator: Dataloader or device max batch size is invalid.
Provided values:
    dataloader_batch_size: 3
    device_max_batch_size: None

2023-11-23 10:38:51 INFO     Navigator: Search for maximal batch size disable. Execute single conversion.
2023-11-23 10:38:51 INFO     Navigator: Command: /home/wzl/miniconda3/bin/python trt-fp32/reproduce_conversion.py --exported_model_path 'onnx/model.onnx' --converted_model_path 'trt-fp32/model.plan' --profiles '[{"X": {"min": (1, 3, 8, 8), "opt": (3, 3, 8, 8), "max": (3, 3, 8, 8)}}]' --max_workspace_size '8589934592' --precision 'fp32' --precision_mode 'hierarchy' --workspace '/home/wzl/github/model_navigator/navigator_workspace' --custom_args '{}'
2023-11-23 10:38:51 INFO     Navigator: Command output:
    [W] Unable to determine GPU memory usage
    [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
    Traceback (most recent call last):
      File "/home/wzl/github/model_navigator/navigator_workspace/trt-fp32/reproduce_conversion.py", line 127, in <module>
        fire.Fire(convert)
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
        component_trace = _Fire(component, args, parsed_flag_args, context, name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
        component, remaining_args = _CallAndUpdateTrace(
                                    ^^^^^^^^^^^^^^^^^^^^
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
        component = fn(*varargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^
      File "/home/wzl/github/model_navigator/navigator_workspace/trt-fp32/reproduce_conversion.py", line 105, in convert
        network = network_from_onnx_path(exported_model_path.as_posix(), flags=onnx_parser_flags)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<string>", line 3, in network_from_onnx_path
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
        return self.call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/polygraphy/util/util.py", line 710, in wrapped
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/polygraphy/backend/trt/loader.py", line 223, in call_impl
        builder, network, parser = super().call_impl()
                                   ^^^^^^^^^^^^^^^^^^^
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/polygraphy/util/util.py", line 710, in wrapped
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/polygraphy/backend/trt/loader.py", line 138, in call_impl
        builder, network = create_network(strongly_typed=self.strongly_typed)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<string>", line 3, in create_network
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
        return self.call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/polygraphy/util/util.py", line 710, in wrapped
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/wzl/miniconda3/lib/python3.11/site-packages/polygraphy/backend/trt/loader.py", line 103, in call_impl
        builder = trt.Builder(trt_util.get_trt_logger())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: pybind11::init(): factory function returned nullptr
```

**Comment by wanglong001** [comment]
```
pip list | grep tensorrt
tensorrt                   8.6.1.post1
```
I pip removed tensorrt and it worked, but I don't know why

**Comment by jkosek** [comment]
@wanglong001 when you removed `tensorrt` package what was the final status of execution? There is a table printed at the end of logs with summary?

**Comment by wanglong001** [comment]
# install tensorrt

```
root@240983e49048:/opt/model_navigator# pip install tensorrt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting tensorrt
  Downloading tensorrt-8.6.1.post1.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tensorrt
  Building wheel for tensorrt (setup.py) ... done
  Created wheel for tensorrt: filename=tensorrt-8.6.1.post1-py2.py3-none-any.whl size=17283 sha256=c4a1e0d039c8f45345b6c5f96b0afc45ad0fcda4b9ce35a61bfe1822b3312944
  Stored in directory: /tmp/pip-ephem-wheel-cache-fd17vn8a/wheels/1e/61/d6/9536ceb9d5509b84a7550d6f7526c3da34886fabb50f41345f
Successfully built tensorrt
Installing collected packages: tensorrt
Successfully installed tensorrt-8.6.1.post1
```
## python3 test.py
```
 [W] Unable to determine GPU memory usage
    [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
    Traceback (most recent call last):
      File "trt-fp32/reproduce_conversion.py", line 127, in <module>
        fire.Fire(convert)
      File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
        component_trace = _Fire(component, args, parsed_flag_args, context, name)
      File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
        component, remaining_args = _CallAndUpdateTrace(
      File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
        component = fn(*varargs, **kwargs)
      File "trt-fp32/reproduce_conversion.py", line 105, in convert
        network = network_from_onnx_path(exported_model_path.as_posix(), flags=onnx_parser_flags)
      File "<string>", line 3, in network_from_onnx_path
      File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 40, in __call__
        return self.call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 710, in wrapped
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 223, in call_impl
        builder, network, parser = super().call_impl()
      File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 710, in wrapped
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 138, in call_impl
        builder, network = create_network(strongly_typed=self.strongly_typed)
      File "<string>", line 3, in create_network
      File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 40, in __call__
        return self.call_impl(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/polygraphy/util/util.py", line 710, in wrapped
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 103, in call_impl
        builder = trt.Builder(trt_util.get_trt_logger())
    TypeError: pybind11::init(): factory function returned nullptr
```

# uninstall tensorrt
```
root@240983e49048:/opt/model_navigator# pip uninstall tensorrt
Found existing installation: tensorrt 8.6.1.post1
Uninstalling tensorrt-8.6.1.post1:
  Would remove:
    /usr/local/lib/python3.8/dist-packages/tensorrt-8.6.1.post1.dist-info/*
    /usr/local/lib/python3.8/dist-packages/tensorrt/*
Proceed (Y/n)? y
  Successfully uninstalled tensorrt-8.6.1.post1
```

## python3 test.py
```
+----------+-------+--------------------+----------------+--------------------------+
| Format   | Key   | Parent Model Key   | Model Status   | Runner Status            |
+==========+=======+====================+================+==========================+
| onnx     | onnx  | Framework          | CopyModel: OK  | OnnxCUDA                 |
|          |       |                    |                |     Correctness: OK      |
|          |       |                    |                |     Performance: OK      |
|          |       |                    |                |     VerifyModel: SKIPPED |
|          |       |                    |                | OnnxTensorRT             |
|          |       |                    |                |     Correctness: OK      |
|          |       |                    |                |     Performance: OK      |
|          |       |                    |                |     VerifyModel: SKIPPED |
+----------+-------+--------------------+----------------+--------------------------+
2023-11-24 01:17:32 WARNING  Navigator: Initially models are not verified. Validate exported models and use PackageDescriptor.set_verified(format, runtime, jit_type, precision) method to set models as verified.
2023-11-24 01:17:32 WARNING  Navigator: Unverified runtime: OnnxCUDA for the onnx model.
2023-11-24 01:17:32 WARNING  Navigator: Unverified runtime: OnnxTensorRT for the onnx model.
2023-11-24 01:17:32 INFO     Navigator:
Strategy: MaxThroughputStrategy
  Latency: 5.3603 [ms]
  Throughput: 5960594.4248 [infer/sec]
  Runner: OnnxCUDA
  Model: onnx/model.onnx
2023-11-24 01:17:32 INFO     Navigator:
Strategy: MinLatencyStrategy
  Latency: 0.2964 [ms]
  Throughput: 13215.5541 [infer/sec]
  Runner: OnnxCUDA
  Model: onnx/model.onnx
```

**Comment by jkosek** [comment]
Thanks @wanglong001. We will take a look and get back to you.

**Comment by wanglong001** [comment]
@jkosek  THS, yesterday， I used older version of TensorRT and tritonserver, it worked.
and found the other issue:

# server
```python


def main():
    package = nav.package.load("onnx_linear.plan", "onnx_workspace")

    pytriton_adapter = nav.pytriton.PyTritonAdapter(
        package=package, strategy=nav.MaxThroughputStrategy()
    )
    runner = pytriton_adapter.runner

    """Runner must be activated before inference."""
    runner.activate()

    # inputs = pytriton.triton.Tensor
    # print(runner.infer({"images": inputs}))

    @batch
    def infer_func(**inputs):
        """Wrap runner inference function and add `@batch` decorator to enable batching."""
        return runner.infer(inputs)

    with Triton() as triton:
        """Load model into Triton Inference Server."""
        triton.bind(
            model_name="linear",
            infer_func=infer_func,
            inputs=pytriton_adapter.inputs,
            outputs=pytriton_adapter.outputs,
            config=pytriton_adapter.config,
        )
        """Serve model through Triton Inference Server."""
        triton.serve()


if __name__ == '__main__':
    main()
```

# client
```python
import logging

import numpy as np
# import torch  # pytype: disable=import-error
from pytriton.client import ModelClient  # pytype: disable=import-error

logger = logging.getLogger("client")
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(name)s: %(message)s")


def main():
    """Prepare data and send inference request to PyTriton server"""

    batch_size = 10
    data_size = (5,)
    # data_batch = torch.randn(size=(batch_size,) + data_size, dtype=torch.float32).numpy()
    images = np.random.randn(1, 3, 224, 224).astype(np.float32)

    """Use PyTriton client to send inference request."""
    with ModelClient("http://127.0.0.1:8000", "linear") as client:
        logger.info("Sending request")
        result_dict = client.infer_batch(input=images)

    logger.info(f"results: {result_dict}")


if __name__ == "__main__":
    main()
```

# error of running client
```
python-BaseException
Traceback (most recent call last):
  File "/home/wzl/miniconda3/lib/python3.11/site-packages/pytriton/client/client.py", line 572, in _infer
    response = self._infer_client.infer(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wzl/miniconda3/lib/python3.11/site-packages/tritonclient/http/_client.py", line 1468, in infer
    _raise_if_error(response)
  File "/home/wzl/miniconda3/lib/python3.11/site-packages/tritonclient/http/_utils.py", line 69, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: [400] Failed to process the request(s) for model instance 'linear_0', message: TritonModelException: Model execute error: Traceback (most recent call last):
  File "/tmp/folderk85AG6/1/model.py", line 210, in execute
    meta_requests = self._put_requests_to_buffer(triton_requests)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/folderk85AG6/1/model.py", line 298, in _put_requests_to_buffer
    requests.append(Request(data=request, parameters=json.loads(triton_request.parameters())))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'c_python_backend_utils.InferenceRequest' object has no attribute 'parameters'


At:
  /tmp/folderk85AG6/1/model.py(239): execute


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wzl/test/14_optimize_and_serve_onnx_and_tensorrt_ensemble_on_pytriton/client.py", line 36, in main
    result_dict = client.infer_batch(input=images)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wzl/miniconda3/lib/python3.11/site-packages/pytriton/client/client.py", line 517, in infer_batch
    return self._infer(inputs or named_inputs, parameters, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wzl/miniconda3/lib/python3.11/site-packages/pytriton/client/client.py", line 589, in _infer
    raise PyTritonClientInferenceServerError(
pytriton.client.exceptions.PyTritonClientInferenceServerError: Error occurred during inference request. Message: Failed to process the request(s) for model instance 'linear_0', message: TritonModelException: Model execute error: Traceback (most recent call last):
  File "/tmp/folderk85AG6/1/model.py", line 210, in execute
    meta_requests = self._put_requests_to_buffer(triton_requests)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/folderk85AG6/1/model.py", line 298, in _put_requests_to_buffer
    requests.append(Request(data=request, parameters=json.loads(triton_request.parameters())))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'c_python_backend_utils.InferenceRequest' object has no attribute 'parameters'


At:
  /tmp/folderk85AG6/1/model.py(239): execute
```

**Comment by jkosek** [comment]
@wanglong001 could you share `nvidia-pytriton` and `tritonclient` packages versions? Thanks!

**Comment by jkosek** [comment]
@wanglong001 please try `pip install nvidia-pytriton` instead. There might be some error with compilation of latest PyTriton on older Triton version.

**Comment by wanglong001** [comment]
@jkosek I commented the parameters, it works, 

![image](https://github.com/triton-inference-server/model_navigator/assets/14817376/30143475-3eb3-49c1-a400-1da4d14e2e18)


I'll ask for another question.

```python

def main():
    package = nav.package.load("onnx_linear.plan", "onnx_workspace")

    pytriton_adapter = nav.pytriton.PyTritonAdapter(
        package=package, strategy=nav.MaxThroughputStrategy()
    )
    runner = pytriton_adapter.runner

    """Runner must be activated before inference."""
    runner.activate()

    # inputs = pytriton.triton.Tensor
    # print(runner.infer({"images": inputs}))

    @batch
    def infer_func(**inputs):
        """Wrap runner inference function and add `@batch` decorator to enable batching."""
        return runner.infer(inputs)

    with Triton() as triton:
        """Load model into Triton Inference Server."""
        triton.bind(
            model_name="linear",
            infer_func=infer_func,
            inputs=pytriton_adapter.inputs,
            outputs=pytriton_adapter.outputs,
            config=pytriton_adapter.config,
        )
        """Serve model through Triton Inference Server."""
        triton.serve()


if __name__ == '__main__':
    main()
```

I1128 11:12:11.432622 3503 model_lifecycle.cc:459] loading: linear:1
W1128 11:12:11.868061 3503 metrics.cc:603] Unable to get power limit for GPU 0. Status:Success, value:0.000000
I1128 11:12:12.673137 3503 python_be.cc:1856] **_TRITONBACKEND_ModelInstanceInitialize: linear_0 (CPU device 0)_**
I1128 11:12:12.852808 3503 model_lifecycle.cc:694] successfully loaded 'linear' version 1
W1128 11:12:12.873159 3503 metrics.cc:603] Unable to get power limit for GPU 0. Status:Success, value:0.000000

Why does the linear model run on the CPU？

**Comment by jkosek** [comment]
@wanglong001 we will take a look at the parameters issue in PyTriton.

Also, what you are seeing:
```
I1128 11:12:12.673137 3503 python_be.cc:1856] TRITONBACKEND_ModelInstanceInitialize: linear_0 (CPU device 0)
```
is a proxy model that run on Triton Server process and communicate with your Python code. The device where model execution happens is controlled on Python code side. In your case you would like to review what is the class of runner instance `pytriton_adapter.runner` and this will show where the Linear model reside. The adapter will select the best format from optimize and make it ready to handle prediction calls.

**Comment by wanglong001** [comment]
@jkosek Actually, the real model inference process is not in triton, but is sent to pytriton_adapter.runner through zmq for inference, is my understanding correct

**Comment by jkosek** [comment]
You are correct @wanglong001. The HTTP/gRPC requests are handled by Triton process and shared to Python process through IPC where the model is executed through `pytriton_adapter.runner`.

**Comment by jkosek** [comment]
@wanglong001 is the issue solved or you are still facing some problems?
