### ISSUE TITLE
Assistance Needed: Errors Encountered While Following Tutorial

### ISSUE THREAD

**Issue by AutoStudyP** [triton-inference-server/model_navigator#38]
I am trying to follow the tutorial from your repository using the Triton server. However, I am encountering the following errors:

# ./optimize.py

Traceback (most recent call last):
  File "./examples/01_optimize_torch_linear_model/./optimize.py", line 17, in <module>
    import model_navigator as nav
  File "/opt/conda/lib/python3.11/site-packages/model_navigator/__init__.py", line 49, in <module>
    from model_navigator.inplace import (  # noqa: F401, F403
  File "/opt/conda/lib/python3.11/site-packages/model_navigator/inplace/__init__.py", line 66, in <module>
    from ..reporting.profile.events import ProfileEvent
  File "/opt/conda/lib/python3.11/site-packages/model_navigator/reporting/profile/__init__.py", line 16, in <module>
    from model_navigator.reporting.profile.report import SimpleReport
  File "/opt/conda/lib/python3.11/site-packages/model_navigator/reporting/profile/report.py", line 36, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 1232, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 1222, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'rich.text.Text'> for field status is not allowed: use default_factory

These errors are appearing even though I followed the provided starter instructions and installed the necessary packages using pip. Do you have any suggestions for how to resolve this issue?

**Comment by piotr-bazan-nv** [comment]
Thanks for reporting the issue. The exception is raised with Python version starting 3.11. We are preparing the fix. In the meantime could you try Python 3.10? Thanks!

**Comment by jkosek** [comment]
@AutoStudyP could you try the recent version? Wa have released the fix.
